BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From ðŸ‘‰v4.50ðŸ‘ˆ onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
results_new/neo125_github_experiment/EleutherAI_gpt-neo-125m/github_ngram_13_<0.8_truncated
Saving results to absolute path: /nfs-share/mk2296/projects/llm_memorisation/mia/mimir/tmp_results/neo125_github_experiment/EleutherAI_gpt-neo-125m/github_ngram_13_<0.8_truncated
LOG: cache_dir is nfs-share/mk2296/llm_memorisation/mia/mimir/cache
Using cache dir nfs-share/mk2296/llm_memorisation/mia/mimir/cache
Loading BASE model EleutherAI/gpt-neo-125m...
Loading mask filling model bert...
MOVING BASE MODEL TO GPU...DONE (2.49s)
Loading dataset the_pile...
the_pile
['writing', 'english', 'german', 'pubmed', 'medpaca']
Traceback (most recent call last):
  File "/nfs-share/mk2296/projects/llm_memorisation/mia/mimir/run.py", line 767, in <module>
    main(config)
  File "/nfs-share/mk2296/projects/llm_memorisation/mia/mimir/run.py", line 532, in main
    data_obj_nonmem, data_nonmember = generate_data(
                                      ^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/projects/llm_memorisation/mia/mimir/run.py", line 431, in generate_data
    data = data_obj.load(
           ^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/projects/llm_memorisation/mia/mimir/mimir/data_utils.py", line 133, in load
    data = datasets.load_dataset(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/load.py", line 1562, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/load.py", line 942, in get_module
    data_files = DataFilesDict.from_patterns(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/data_files.py", line 721, in from_patterns
    else DataFilesList.from_patterns(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/data_files.py", line 624, in from_patterns
    resolve_pattern(
  File "/nfs-share/mk2296/poetry/Cache/virtualenvs/mimir-Sp_lKhLC-py3.12/lib/python3.12/site-packages/datasets/data_files.py", line 411, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/nfs-share/mk2296/llm_memorisation/mia/mimir/source/pile/test.jsonl.zst'
